/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Sillanegra({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/sillanegrosca.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.koltuk.geometry}
        material={materials.chair}
        rotation={[0, -0.5, 0]}
      />
    </group>
  );
}

useGLTF.preload("/sillanegrosca.gltf");
