/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/couch.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Pillow002.geometry} material={materials.PillowMaterial} position={[-0.35, 0.9, 0.85]} rotation={[0, 0.44, -1]} scale={0.21} />
      <mesh geometry={nodes.Pillow001.geometry} material={materials.PillowMaterial} position={[-0.39, 0.78, -0.85]} rotation={[0.07, -0.63, -1.01]} scale={0.21} />
      <group position={[-0.37, 0.48, -0.13]} rotation={[0, 0.02, 0]}>
        <mesh geometry={nodes.Cylinder021.geometry} material={materials.CouchFootMaterial} />
        <mesh geometry={nodes.Cylinder021_1.geometry} material={materials['CouchClothGreyMaterial.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/couch.glb')
